// Package git reads local Git history using only os/exec — zero external dependencies.
//
// KEY DESIGN: ONE git log call for the entire analysis window.
// Parsing happens in Go. ~500x faster than calling `git log -- <file>` per file.
//
// v1.1: --numstat replaces --name-only to capture lines added/deleted per commit.
package git

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"time"
)

// ── Skip lists ────────────────────────────────────────────────────────────────

var skipExtensions = map[string]bool{
	".png": true, ".jpg": true, ".jpeg": true, ".gif": true, ".webp": true,
	".svg": true, ".ico": true, ".woff": true, ".woff2": true, ".ttf": true,
	".eot": true, ".otf": true, ".zip": true, ".tar": true, ".gz": true,
	".bz2": true, ".7z": true, ".exe": true, ".dll": true, ".so": true,
	".dylib": true, ".class": true, ".pyc": true, ".pyo": true,
	".pdf": true, ".doc": true, ".docx": true, ".xls": true, ".xlsx": true,
	".lock": true, ".sum": true, ".map": true, ".db": true, ".sqlite": true,
	".DS_Store": true,
}

var skipDirs = map[string]bool{
	"node_modules": true, "vendor": true, ".git": true, "__pycache__": true,
	"dist": true, "build": true, ".next": true, ".nuxt": true, "coverage": true,
	".venv": true, "venv": true, "env": true, ".cache": true, ".idea": true,
	".vscode": true, "bower_components": true, "jspm_packages": true, "target": true,
	".mule":             true, // local Mule runtime cache
	"exchange-docs":     true, // auto-generated Anypoint Exchange docs
	"autogenerated":     true, // system-generated DataWeave/weave output
	"application-types": true, // Mule DataMapper type descriptors — system-generated
}

var criticalPatterns = []string{
	"payment", "billing", "stripe", "checkout", "invoice", "subscription",
	"auth", "authn", "authz", "security", "password", "token",
	"oauth", "jwt", "session", "credential", "secret", "encrypt",
	"migration", "schema", "model", "database",
	"settings", "config",
	"core", "engine", "pipeline", "processor",
	"router", "middleware", "gateway",
	"deploy", "dockerfile",
	"api-gateway", "api-spec", "raml",
	"connector", "global-config",
	"error-handler", "exception",
	"dataweave", "transform",
	"scheduler", "batch",
	// CloudHub 4.0 / Mule 4 critical paths
	"global-config", "global",
	"api-main", "interface",
	"error-handler", "on-error",
	"oauth2", "client-credentials", "client-id",
	"dataweave", "dwl",
	"connector",
	"mule-artifact", // deployment descriptor
	"cloudhub",      // CloudHub-specific config
	"scheduler",
	"batch",
	"anypoint-mq", "jms",
}

// ── Bot detection ─────────────────────────────────────────────────────────────

var botPatterns = []string{
	"dependabot", "renovate", "greenkeeper", "snyk",
	"github-actions", "gitlab-ci", "jenkins",
	"noreply", "no-reply", "[bot]",
	"semantic-release", "release-bot",
	"codecov", "coveralls", "mergify",
	"depfu", "imgbot", "allcontributors",
	"web-flow@github.com",
}

// RepoType identifies the primary technology stack of a repository.
type RepoType string

const (
	RepoTypeGeneral  RepoType = "general"
	RepoTypeMuleSoft RepoType = "mulesoft"
)

// DetectRepoType inspects file paths in the repo to identify the stack.
// MuleSoft repos are identified by the presence of .xml Mule config files,
// mule-artifact.json, or src/main/mule/ directory structure.
func DetectRepoType(repoRoot string) RepoType {
	// Check for mule-artifact.json (definitive MuleSoft marker)
	indicators := []string{
		"mule-artifact.json",
		"src/main/mule",
		"src/main/resources/api",
	}
	for _, indicator := range indicators {
		full := filepath.Join(repoRoot, indicator)
		if _, err := os.Stat(full); err == nil {
			return RepoTypeMuleSoft
		}
	}

	// Check git-tracked file list for .xml mule configs
	out, err := runGit([]string{"ls-files", "--", "*.xml"}, repoRoot)
	if err == nil {
		for _, line := range strings.Split(out, "\n") {
			lower := strings.ToLower(line)
			if strings.Contains(lower, "src/main/mule") ||
				strings.Contains(lower, "global-config") ||
				strings.Contains(lower, "mule-artifact") {
				return RepoTypeMuleSoft
			}
		}
	}

	return RepoTypeGeneral
}

// IsBotEmail returns true if the email matches a known bot or CI service pattern.
func IsBotEmail(email string) bool {
	lower := strings.ToLower(email)
	for _, pattern := range botPatterns {
		if strings.Contains(lower, pattern) {
			return true
		}
	}
	return false
}

// ── Low-impact path detection ─────────────────────────────────────────────────

// lowImpactDirs are directories whose modules should be flagged as low-impact.
// These paths typically contain templates, examples, demos, generated code, or
// documentation — not production runtime code. A BF=1 in examples/ is noise;
// a BF=1 in src/payments/ is a real risk.
var lowImpactDirs = map[string]bool{
	"examples":      true,
	"example":       true,
	"templates":     true,
	"template":      true,
	"demos":         true,
	"demo":          true,
	"samples":       true,
	"sample":        true,
	"docs":          true,
	"doc":           true,
	"stories":       true,
	"storybook":     true,
	".storybook":    true,
	"fixtures":      true,
	"snapshots":     true,
	"__snapshots__": true,
	"__fixtures__":  true,
	"__mocks__":     true,
	"mocks":         true,
	"registry":      true,
	"blocks":        true,
	"playground":    true,
	"sandbox":       true,
	"sketches":      true,
	"prototypes":    true,
	"prototype":     true,
	"benchmarks":    true,
	"benchmark":     true,
	"scripts":       true,
	"tools":         true,
	"hack":          true,
	"contrib":       true,
	"third_party":   true,
	"third-party":   true,
	"generated":     true,
	"gen":           true,
	"__generated__": true,
	"exchange-docs": true,
	"munit":         true,
	"autodiscovery": true,
}

// IsLowImpactPath returns true if the module path is in a low-impact directory.
// These modules are still analyzed but flagged so that risk alerts can distinguish
// "real" operational risk from template/example noise.
func IsLowImpactPath(modulePath string) bool {
	normalized := filepath.ToSlash(strings.ToLower(modulePath))
	parts := strings.Split(normalized, "/")

	for _, part := range parts {
		if lowImpactDirs[part] {
			return true
		}
	}
	return false
}

const commitSep = "<<KINLYZE>>"

// ── Package-level compiled regex ──────────────────────────────────────────────

// dateRegex normalizes timezone offsets without colons (e.g. +0530 → +05:30).
var dateRegex = regexp.MustCompile(`(\d{2}:\d{2}:\d{2}) ([+-]\d{2})(\d{2})$`)

// ── Public types ──────────────────────────────────────────────────────────────

// RepoInfo holds basic repository metadata.
type RepoInfo struct {
	Name         string    `json:"name"`
	Branch       string    `json:"branch"`
	TotalCommits int       `json:"total_commits"`
	FirstCommit  time.Time `json:"first_commit"`
	LastCommit   time.Time `json:"last_commit"`
}

// Commit is a single commit record attached to a file.
type Commit struct {
	SHA          string
	Email        string
	Name         string
	Date         time.Time
	LinesAdded   int
	LinesDeleted int
}

// LinesChanged returns the total lines modified in this commit (adds + deletes).
func (c Commit) LinesChanged() int {
	return c.LinesAdded + c.LinesDeleted
}

// Contributor is a developer with their all-time commit count.
type Contributor struct {
	Name    string
	Email   string
	Commits int
}

// ── Git runner ────────────────────────────────────────────────────────────────

func runGit(args []string, cwd string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = cwd
	out, err := cmd.Output()
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("git %s: %s", args[0], string(exitErr.Stderr))
		}
		return "", fmt.Errorf("git not found: %w", err)
	}
	return string(out), nil
}

// ── Repo validation ───────────────────────────────────────────────────────────

// IsGitRepo returns true if path is inside a git repository.
func IsGitRepo(path string) bool {
	_, err := runGit([]string{"rev-parse", "--git-dir"}, path)
	return err == nil
}

// GetRepoRoot returns the absolute path to the repo root.
func GetRepoRoot(path string) (string, error) {
	out, err := runGit([]string{"rev-parse", "--show-toplevel"}, path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(out), nil
}

// GetRepoInfo returns basic repo metadata.
func GetRepoInfo(repoRoot string) (RepoInfo, error) {
	info := RepoInfo{}

	// Branch
	branch, err := runGit([]string{"rev-parse", "--abbrev-ref", "HEAD"}, repoRoot)
	if err != nil {
		info.Branch = "unknown"
	} else {
		info.Branch = strings.TrimSpace(branch)
	}

	// Total commits
	countOut, err := runGit([]string{"rev-list", "--count", "HEAD"}, repoRoot)
	if err != nil {
		return info, fmt.Errorf("repository has no commits")
	}
	if _, err := fmt.Sscanf(strings.TrimSpace(countOut), "%d", &info.TotalCommits); err != nil {
		return info, fmt.Errorf("could not parse commit count: %w", err)
	}
	if info.TotalCommits == 0 {
		return info, fmt.Errorf("repository has no commits")
	}

	// Name from root path
	info.Name = filepath.Base(repoRoot)

	// First and last commit dates
	if last, err := runGit([]string{"log", "--format=%ai", "--max-count=1"}, repoRoot); err == nil {
		info.LastCommit = parseDate(strings.TrimSpace(last))
	}
	if first, err := runGit([]string{"log", "--reverse", "--format=%ai", "--max-count=1"}, repoRoot); err == nil {
		info.FirstCommit = parseDate(strings.TrimSpace(first))
	}

	return info, nil
}

// ── File helpers ──────────────────────────────────────────────────────────────

// skipFileStems are filenames (without extension) that should never be analyzed,
// regardless of which directory they live in.
var skipFileStems = map[string]bool{
	"application-types": true, // Mule DataMapper type descriptors — system-generated
}

// ShouldAnalyze returns true if this file path is worth analyzing.
func ShouldAnalyze(path string) bool {
	normalized := filepath.ToSlash(path)
	parts := strings.Split(normalized, "/")

	// Check parent directories
	for _, part := range parts[:max(0, len(parts)-1)] {
		if skipDirs[strings.ToLower(part)] {
			return false
		}
	}

	// Check extension
	ext := strings.ToLower(filepath.Ext(path))
	if skipExtensions[ext] {
		return false
	}

	// Check filename stem
	filename := parts[len(parts)-1]
	stem := strings.TrimSuffix(strings.ToLower(filename), strings.ToLower(filepath.Ext(filename)))
	if skipFileStems[stem] {
		return false
	}

	return len(filename) > 0
}

// IsCriticalFile returns true if the file path matches a critical pattern.
func IsCriticalFile(path string) bool {
	lower := strings.ToLower(path)
	for _, p := range criticalPatterns {
		if strings.Contains(lower, p) {
			return true
		}
	}
	return false
}

// GetModulePath returns the parent directory of a file path.
// "src/payments/processor.go" → "src/payments"
// "main.go"                   → "root"
func GetModulePath(filePath string) string {
	normalized := filepath.ToSlash(filePath)
	idx := strings.LastIndex(normalized, "/")
	if idx < 0 {
		return "root"
	}
	return normalized[:idx]
}

// GetMuleModulePath returns a module key tuned for MuleSoft repos.
// Rules (in order):
//
//  1. Mule flow XML (src/main/mule/) → filename stem
//     src/main/mule/customer-main.xml      → "customer-main"
//
//  2. DataWeave files → "dwl/<stem>"
//     src/main/resources/dwl/order-map.dwl → "dwl/order-map"
//
//  3. Files under src/main/resources/ → strip that prefix so the module
//     name reflects only the sub-folder or filename, never the full path.
//     src/main/resources/config/dev.yaml   → "config"
//     src/main/resources/api/api.raml      → "api"
//     src/main/resources/log4j2.xml        → "log4j2"  (filename stem)
//
//  4. Everything else → standard directory-based grouping
func GetMuleModulePath(filePath string) string {
	normalized := filepath.ToSlash(filePath)
	lower := strings.ToLower(normalized)

	// Rule 1: Mule flow XML files → filename stem
	if strings.HasSuffix(lower, ".xml") && strings.Contains(lower, "src/main/mule") {
		base := filepath.Base(normalized)
		return strings.TrimSuffix(base, filepath.Ext(base))
	}

	// Rule 2: DataWeave files → "dwl/<stem>"
	if strings.HasSuffix(lower, ".dwl") {
		base := filepath.Base(normalized)
		return "dwl/" + strings.TrimSuffix(base, filepath.Ext(base))
	}

	// Rule 3: src/main/resources/** → strip the resources prefix
	const resourcesPrefix = "src/main/resources/"
	if idx := strings.Index(lower, resourcesPrefix); idx >= 0 {
		rel := normalized[idx+len(resourcesPrefix):]
		if rel == "" {
			// File is literally named "resources" — unlikely, but safe fallback
			return "resources"
		}
		// Has a sub-directory: return that directory name
		if slashIdx := strings.Index(rel, "/"); slashIdx > 0 {
			return rel[:slashIdx]
		}
		// File sits directly in src/main/resources/ → use filename stem
		base := filepath.Base(rel)
		return strings.TrimSuffix(base, filepath.Ext(base))
	}

	return GetModulePath(filePath)
}

// MuleSoftLayer represents the API-led connectivity tier of a MuleSoft project.
type MuleSoftLayer string

const (
	MuleSoftLayerExperience MuleSoftLayer = "Experience Layer"
	MuleSoftLayerProcess    MuleSoftLayer = "Process Layer"
	MuleSoftLayerSystem     MuleSoftLayer = "System Layer"
	MuleSoftLayerUnknown    MuleSoftLayer = ""
)

// DetectMuleSoftLayer infers the API-led connectivity layer from the repo name.
// In Mule, teams name repos after the API they expose:
//
//	customer-exp-api  → Experience Layer  (consumer-facing)
//	order-prc-api     → Process Layer     (orchestration)
//	inventory-sys-api → System Layer      (system-of-record adapter)
func DetectMuleSoftLayer(repoName string) MuleSoftLayer {
	name := strings.ToLower(repoName)
	switch {
	case strings.Contains(name, "exp-api") ||
		strings.Contains(name, "experience-api") ||
		strings.Contains(name, "-exp-"):
		return MuleSoftLayerExperience
	case strings.Contains(name, "prc-api") ||
		strings.Contains(name, "process-api") ||
		strings.Contains(name, "-prc-"):
		return MuleSoftLayerProcess
	case strings.Contains(name, "sys-api") ||
		strings.Contains(name, "system-api") ||
		strings.Contains(name, "-sys-"):
		return MuleSoftLayerSystem
	}
	return MuleSoftLayerUnknown
}

// GetContributors returns all-time contributors sorted by commit count.
func GetContributors(repoRoot string) ([]Contributor, error) {
	out, err := runGit([]string{"shortlog", "-sne", "--all", "--no-merges"}, repoRoot)
	if err != nil {
		return nil, err
	}

	re := regexp.MustCompile(`^\s*(\d+)\s+(.+?)\s+<(.+?)>\s*$`)
	var contributors []Contributor

	for _, line := range strings.Split(out, "\n") {
		m := re.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		var count int
		if _, err := fmt.Sscanf(m[1], "%d", &count); err != nil {
			continue
		}
		contributors = append(contributors, Contributor{
			Commits: count,
			Name:    strings.TrimSpace(m[2]),
			Email:   strings.ToLower(strings.TrimSpace(m[3])),
		})
	}

	sort.Slice(contributors, func(i, j int) bool {
		return contributors[i].Commits > contributors[j].Commits
	})
	return contributors, nil
}

// ── Bulk commit loader ────────────────────────────────────────────────────────

// LoadCommitsBulk loads ALL commits for the window in a single git log call.
// Uses --numstat to capture lines added/deleted per file per commit.
// Returns map[filePath][]Commit.
func LoadCommitsBulk(repoRoot string, sinceDays int, progressFn func(string)) (map[string][]Commit, error) {
	if progressFn != nil {
		progressFn(fmt.Sprintf("Running git log (last %d days)...", sinceDays))
	}

	format := commitSep + "%n%H%n%ae%n%an%n%ai"
	args := []string{
		"log",
		fmt.Sprintf("--since=%d days ago", sinceDays),
		fmt.Sprintf("--format=%s", format),
		"--numstat",
		"--no-merges",
		"--diff-filter=AM",
	}

	out, err := runGit(args, repoRoot)
	if err != nil {
		return map[string][]Commit{}, nil // non-fatal — return empty
	}

	if progressFn != nil {
		progressFn("Parsing commit history...")
	}

	return parseBulkLog(out), nil
}

// LoadCommitsWindow loads commits in [untilDays, sinceDays] window for trend comparison.
func LoadCommitsWindow(repoRoot string, sinceDays, untilDays int) map[string][]Commit {
	format := commitSep + "%n%H%n%ae%n%an%n%ai"
	args := []string{
		"log",
		fmt.Sprintf("--since=%d days ago", sinceDays),
		fmt.Sprintf("--format=%s", format),
		"--numstat",
		"--no-merges",
		"--diff-filter=AM",
	}
	if untilDays > 0 {
		args = append(args[:2], append([]string{fmt.Sprintf("--until=%d days ago", untilDays)}, args[2:]...)...)
	}

	out, err := runGit(args, repoRoot)
	if err != nil {
		return map[string][]Commit{}
	}
	return parseBulkLog(out)
}

// parseBulkLog parses git log --numstat output into {filePath: []Commit}.
// State machine: seek → sha → email → name → date → files → repeat
//
// --numstat format per file line: "added\tdeleted\tpath"
// Binary files show as: "-\t-\tpath"
func parseBulkLog(raw string) map[string][]Commit {
	result := make(map[string][]Commit)

	type commitState struct {
		sha   string
		email string
		name  string
		date  time.Time
	}

	var current *commitState
	state := "seek"

	scanner := bufio.NewScanner(strings.NewReader(raw))
	scanner.Buffer(make([]byte, 10*1024*1024), 10*1024*1024)

	for scanner.Scan() {
		line := strings.TrimRight(scanner.Text(), "\r")

		if line == commitSep {
			current = &commitState{}
			state = "sha"
			continue
		}

		if current == nil {
			continue
		}

		switch state {
		case "sha":
			if len(line) >= 8 {
				current.sha = line[:8]
			}
			state = "email"
		case "email":
			current.email = strings.ToLower(strings.TrimSpace(line))
			state = "name"
		case "name":
			current.name = strings.TrimSpace(line)
			state = "date"
		case "date":
			current.date = parseDate(line)
			state = "files"
		case "files":
			if line == "" {
				continue
			}

			// Parse numstat line: "added\tdeleted\tpath"
			parts := strings.SplitN(line, "\t", 3)
			if len(parts) != 3 {
				continue
			}

			filePath := parts[2]

			// Handle rename paths like "{old => new}/file.go" — extract final path
			if strings.Contains(filePath, " => ") {
				filePath = cleanRenamePath(filePath)
			}

			// Parse line counts (binary files show "-" which becomes 0)
			added, _ := strconv.Atoi(parts[0])
			deleted, _ := strconv.Atoi(parts[1])

			if ShouldAnalyze(filePath) && current.email != "" {
				result[filePath] = append(result[filePath], Commit{
					SHA:          current.sha,
					Email:        current.email,
					Name:         current.name,
					Date:         current.date,
					LinesAdded:   added,
					LinesDeleted: deleted,
				})
			}
		}
	}

	return result
}

// cleanRenamePath extracts the destination path from a git rename notation.
// "{old => new}/file.go"  → "new/file.go"
// "dir/{a.go => b.go}"   → "dir/b.go"
func cleanRenamePath(path string) string {
	// Handle {old => new} syntax
	re := regexp.MustCompile(`\{[^}]*\s*=>\s*([^}]*)\}`)
	cleaned := re.ReplaceAllString(path, "$1")
	// Clean up double slashes
	cleaned = strings.ReplaceAll(cleaned, "//", "/")
	cleaned = strings.TrimPrefix(cleaned, "/")
	return cleaned
}

// ── Date parsing ──────────────────────────────────────────────────────────────

var dateFormats = []string{
	"2006-01-02 15:04:05 -0700",
	"2006-01-02 15:04:05 -07:00",
	"2006-01-02T15:04:05-07:00",
	"2006-01-02T15:04:05Z",
}

func parseDate(s string) time.Time {
	s = strings.TrimSpace(s)
	// Normalize "2024-01-15 14:30:00 +0530" timezone format
	s = dateRegex.ReplaceAllString(s, "$1 $2:$3")

	for _, format := range dateFormats {
		if t, err := time.Parse(format, s); err == nil {
			return t
		}
	}
	return time.Time{}
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// IsWindows returns true on Windows (used for terminal width detection).
func IsWindows() bool {
	return runtime.GOOS == "windows"
}
